### ISSUE TITLE
Docstrings Losses

### ISSUE THREAD

**Issue by DrashtySoni** [unifyai/ivy#2331]
As explained in the function reformatting [open task](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting), each function in the [losses](https://github.com/unifyai/ivy/blob/master/ivy/container/losses.py) submodule should be updated to follow the implementation instructions given in the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) section of the docs. The updates should be applied for both the [Ivy API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#ivy-api) and [Backend API](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#backend-api). The [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) is the best general resource for learning in detail how functions should be implemented. Many of the functions are not implemented as they should be. You will need to make changes to the current implementations, but you do not need to go through all sections of the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html). Specifically, you should make the following changes, where appropriate:

1. update the [function arguments](https://lets-unify.ai/ivy/deep_dive/9_function_arguments.html) and type hints.
2. add the correct [docstrings](https://lets-unify.ai/ivy/deep_dive/10_docstrings.html)
3. add thorough [docstring examples](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html)

- [ ] #1221  static_cross_entropy
- [ ] #2112 cross_entropy
- [ ] #6996 static_binary_cross_entropy 
- [ ] #9669 binary_cross_entropy
- [ ] #3003 static_sparse_cross_entropy
- [ ] #0330 sparse_cross_entropy
