### ISSUE TITLE
Fixing tests

### ISSUE THREAD

**Issue by nassimberrada** [unifyai/ivy#6397]
### Overview

Fix failing unit tests for Ivy’s functional API and stateful API. You should use the [functional core API dashboard](https://github.com/unifyai/ivy/blob/dashboard/test_dashboards/functional_core_dashboard.md), [functional neural net API dashboard](https://github.com/unifyai/ivy/blob/dashboard/test_dashboards/functional_nn_dashboard.md) and the [stateful API dashboard](https://github.com/unifyai/ivy/blob/dashboard/test_dashboards/stateful_dashboard.md) in order to quickly find functions to work on.

### Task details

Recently, some fixes were made to our CI pipeline, which enabled the data sampling to be “remembered” by hypothesis across multiple commits. This greatly improved the power of our hypothesis testing, enabling deep searches of the data generated in order to find complex test failures. We also recently improved our CI dashboards.

### Working on a function

Once you have chosen to work on a particular function, you should add it to this list, create an issue from the newly added element, and assign yourself to that issue.
As soon as the test is fixed, you should remove function from the list as there is no need to keep a record of it. Once the task is completed, both dashboards will show only green ticks.

### Functions being worked on

- [ ] ivy.stable_pow
- [ ] ivy.stateful.Layers
- [ ] ivy.stateful.Optimizers
- [ ] ivy.stateful.Norms (all backends)
- [ ] ivy.linalg (linear algebra)
- [ ] ivy.stateful.Sequential
