### ISSUE TITLE
Impove meta docstrings

### ISSUE THREAD

**Issue by Ishticode** [unifyai/ivy#756]
The docstrings for all [meta](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/meta.py) functions should be modified to use the NumPy style, and also include examples for using the method.

- [ ] _compute_cost_and_update_grads
- [ ] _train_task
- [ ]  _train_tasks_batched
- [ ] _train_tasks_with_for_loop
- [ ] _train_tasks
- [ ] fomaml_step
- [ ] reptile_step
- [ ] maml_step

**Comment by suryathecreator** [comment]
Reformat meta #756 #1969

**Comment by suryathecreator** [comment]
_compute_cost_and_update_grads #1969

**Comment by arvinnick** [comment]
fomaml_step #2142

**Comment by VikramxD** [comment]
- [ ] #2380

**Comment by saifurrehman4114** [comment]
- [ ] #8890

**Comment by moshesimon** [comment]
- [ ] #10498

**Comment by arlou022** [comment]
- [ ] #13205

**Comment by cullenoc** [comment]
- [ ] #14980

**Comment by Rexon-Pambujya** [comment]
#16167

**Comment by rereversed** [comment]
- cost_fn_with_variables #18275

**Comment by SandhyaDassaye1** [comment]
#23485

**Comment by SandhyaDassaye1** [comment]
#23486

**Comment by Camp-ione** [comment]
- [ ] #23491

**Comment by ukj02** [comment]
- [] #23745

**Comment by nsethi167** [comment]
maml_step #26634

**Comment by SandhyaDassaye1** [comment]
- [ ] #27097
